### ISSUE TITLE
Hi Mega!

### ISSUE THREAD

**Issue by IamTregsthedev** [MegaCode18/scar#1]
Hey,

I helped with elme3ntalcode,and was wondering if I could help you with this! I got better in my developing skill!

**Comment by MegaCode18** [comment]
Thanks for offering! Currently, I'm still not sure what I'll do for this project, but perhaps in the near future! 😃

**Comment by MegaCode18** [comment]
Closing this issue to prevent it from cluttering the actual issues.

**Comment by IamTregsthedev** [comment]
Hey, I can help and help you decide what to do with this project, Make a Website, and more

**Comment by MegaCode18** [comment]
Currently, I'm a bit busy with other projects, but I may come back to this in a few weeks or so.
